import 'package:flutter/material.dart';

class AppLanguage {
  final String code;
  final String name;
  final String nativeName;
  final Locale locale;

  const AppLanguage({
    required this.code,
    required this.name,
    required this.nativeName,
    required this.locale,
  });
}

class AppLanguages {
  static const supported = <AppLanguage>[
    AppLanguage(
      code: 'en',
      name: 'English',
      nativeName: 'English',
      locale: Locale('en'),
    ),
    AppLanguage(
      code: 'hi',
      name: 'Hindi',
      nativeName: 'हिन्दी',
      locale: Locale('hi'),
    ),
    AppLanguage(
      code: 'as',
      name: 'Assamese',
      nativeName: 'অসমীয়া',
      locale: Locale('as'),
    ),
    AppLanguage(
      code: 'bn',
      name: 'Bengali',
      nativeName: 'বাংলা',
      locale: Locale('bn'),
    ),
    AppLanguage(
      code: 'mni',
      name: 'Meitei',
      nativeName: 'মৈতৈলোন্',
      locale: Locale('mni'),
    ),
    AppLanguage(
      code: 'kha',
      name: 'Khasi',
      nativeName: 'Khasi',
      locale: Locale('kha'),
    ),
    AppLanguage(
      code: 'lus',
      name: 'Mizo',
      nativeName: 'Mizo',
      locale: Locale('lus'),
    ),
    AppLanguage(
      code: 'ne',
      name: 'Nepali',
      nativeName: 'नेपाली',
      locale: Locale('ne'),
    ),
    AppLanguage(
      code: 'nag',
      name: 'Nagamese',
      nativeName: 'Nagamese',
      locale: Locale('nag'),
    ),
  ];

  static AppLanguage byCode(String code) {
    return supported.firstWhere(
      (language) => language.code == code,
      orElse: () => supported.first,
    );
  }
}

class AppLocalizations {
  final String languageCode;

  const AppLocalizations(this.languageCode);

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    final result = Localizations.of<AppLocalizations>(
      context,
      AppLocalizations,
    );

    return result ?? const AppLocalizations('en');
  }

  String get(String key) {
    return _translations[languageCode]?[key] ??
        _translations['en']?[key] ??
        key;
  }

  String languageName(String code) {
    return AppLanguages.byCode(code).name;
  }

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      // App & Home
      'appTitle': 'MedSync OA Screening',
      'selectLanguage': 'Select Language',
      'language': 'Language',
      'movementHealth': 'Digital Knee Health Screening',
      'understandKneeMovement': 'Understand your knee movement & joint health',
      'heroDescription':
          'Quick, non-invasive digital screening combining patient symptoms with wearable IMU movement analysis.',
      'howItWorks': 'How MedSync Works',
      'tellUsHowYouFeel': '1. Tell Us How You Feel',
      'tellUsHowYouFeelDescription':
          'Answer a short symptom assessment regarding knee pain, stiffness, and daily activity limits.',
      'setUpMovementSensors': '2. Set Up Movement Sensors',
      'setUpMovementSensorsDescription':
          'Connect the MedSync KneeBand dual-IMU wearable or start in demo simulation mode.',
      'completeMovementTests': '3. Complete Movement Tests',
      'completeMovementTestsDescription':
          'Perform a 30-Second Chair Stand and a 20m Fast Walk with real-time feedback.',
      'getAiAssessment': '4. Get AI Risk Screening',
      'getAiAssessmentDescription':
          'Receive an instant kinematic summary, data quality score, and clinical screening report.',
      'designedToSupport': 'Designed for Clinical Support',
      'supportDescription':
          'MedSync assists healthcare providers with objective movement quantitative metrics for preliminary screening.',
      'preliminaryDisclaimer':
          'MedSync provides preliminary screening metrics and is not a replacement for clinical diagnosis.',
      'cancelScreening': 'Cancel Screening',
      'step1Of4': 'Step 1 of 4',
      'step2Of4': 'Step 2 of 4',
      'step3Of4': 'Step 3 of 4',
      'step4Of4': 'Step 4 of 4',

      // General Buttons
      'continue': 'CONTINUE',
      'back': 'BACK',
      'next': 'NEXT',
      'done': 'DONE',
      'cancel': 'CANCEL',
      'start': 'START',
      'stop': 'STOP',
      'retry': 'RETRY',
      'save': 'SAVE',
      'close': 'CLOSE',
      'yes': 'Yes',
      'no': 'No',
      'notAvailable': 'Not available',

      // Assessment
      'patientAssessment': 'Patient Assessment',
      'patientAssessmentTitle': 'Tell us about your symptoms',
      'patientAssessmentSubtitle':
          'This information is combined with movement data for AI-assisted preliminary screening.',
      'age': 'Age',
      'sex': 'Sex',
      'female': 'Female',
      'male': 'Male',
      'preferNotToSay': 'Prefer not to say',
      'height': 'Height',
      'weight': 'Weight',
      'bmi': 'BMI',
      'pain': 'Pain',
      'stiffness': 'Stiffness',
      'functionalDifficulty': 'Functional difficulty',
      'activityRelatedPain': 'Pain related to activity',
      'morningStiffness': 'Morning stiffness',
      'enterAge': 'Enter age',
      'enterHeight': 'Enter height',
      'enterWeight': 'Enter weight',
      'selectSex': 'Select sex',
      'ratePain': 'Rate your pain',
      'rateStiffness': 'Rate your stiffness',
      'rateDifficulty': 'Rate your difficulty with movement',

      // Screening & Setup
      'readyForScreening': 'Ready for Screening?',
      'screeningIncludes':
          'The screening includes a chair stand and a fast walk movement assessment.',
      'startScreening': 'START SCREENING',
      'screeningComplete': 'SCREENING COMPLETE',
      'screeningDataCollected': 'Screening Data Collected',
      'sensorSetup': 'Sensor Setup',
      'connectSensors': 'Connect Sensors',
      'sensorConnection': 'Sensor Connection',
      'connectToSensors':
          'Connect the wearable sensors before starting the movement assessment.',
      'thighSensor': 'Thigh sensor',
      'shinSensor': 'Shin sensor',
      'connected': 'Connected',
      'disconnected': 'Disconnected',
      'searching': 'Searching...',
      'connecting': 'Connecting...',
      'connectionSuccessful': 'Sensor connection successful.',
      'connectionFailed': 'Sensor connection failed.',
      'checkBluetooth':
          'Please check Bluetooth and make sure the sensors are powered on.',
      'chooseSensorSource': 'Choose Sensor Source',
      'sensorSourceDescription':
          'Select between physical KneeBand BLE wearable sensors or interactive demo mode.',
      'demoMode': 'Demo Simulation Mode',
      'demoModeSubtitle': 'Simulated dual-IMU kinematic data',
      'demoModeDescription':
          'Ideal for exploring features without physical hardware connected.',
      'wearableMode': 'KneeBand BLE Wearable',
      'wearableModeSubtitle': 'Live hardware streaming',
      'wearableModeDescription':
          'Connect the KneeBand dual-IMU device over Bluetooth Low Energy.',
      'kneeBandConnection': 'KneeBand Connection',
      'connectKneeBand': 'Connect KneeBand',
      'kneeBandConnected': 'KneeBand Connected',
      'wearableReadyMessage': 'The wearable is ready to stream IMU data.',
      'connectWearableMessage':
          'Power on the KneeBand hardware and enable Bluetooth on your phone.',
      'connectionStatus': 'Connection Status',
      'wearableDevice': 'Wearable Device',
      'esp32PowerNotice':
          'Make sure the ESP32 is powered on and advertising as KneeBand_OA.',
      'scanForDevices': 'SCAN FOR DEVICES',
      'availableDevices': 'Available Devices',
      'reconnect': 'RECONNECT',

      // Calibration
      'calibration': 'Calibration',
      'calibrating': 'Calibrating Gyros...',
      'standStill': 'Stand still while the sensors calibrate.',
      'calibrationComplete': 'Calibration complete.',
      'calibrationFailed': 'Calibration failed.',
      'keepStill': 'Please remain still during calibration.',
      'keepLegStillCalibration':
          'Keep your leg completely still for 2 seconds while gyro offsets are calculated.',

      // Movement tests & Tutorial
      'movementAssessment': 'Movement Assessment',
      'movementTests': 'Movement Tests',
      'chairStand': '30-Second Chair Stand',
      'fastWalk': 'Fast Walk',
      'fastWalk20m': '20m Fast Walk',
      'chairStandInstruction':
          'Sit on a firm chair and stand up fully, then sit down repeatedly for 30 seconds.',
      'fastWalkInstruction':
          'Walk quickly and safely in a straight line for 20 metres. Stop at the line.',
      'sitStandRepeatedly': 'Stand up and sit down repeatedly for 30 seconds.',
      'walkQuickly': 'Walk quickly and safely for 20 metres.',
      'keepSensorsSecure':
          'Make sure both thigh and shin sensors are securely strapped on.',
      'followInstructions': 'Follow the instructions shown on screen.',
      'safetyFirst':
          'Stop immediately if you experience severe pain or instability.',
      'getReady': 'GET READY',
      'testRunning': 'TEST RUNNING',
      'testCompleted': 'TEST COMPLETED',
      'testFailed': 'TEST FAILED',
      'ready': 'READY',
      'samplesCollected': 'Samples collected',
      'duration': 'Duration',
      'samplingRate': 'Sampling rate',
      'startTest': 'START TEST',
      'stopTest': 'STOP TEST',
      'watchTutorial': 'Watch Tutorial',
      'tutorial': 'Test Animation Tutorial',
      'howToPerform': 'How to perform this test',
      'sensorData': 'Live Kinematic Data',
      'sensorsReady': 'Sensors calibrated and ready.',
      'positionAndPrepare': 'Position yourself and prepare to begin.',
      'continueMovement': 'Maintain continuous steady movement.',
      'points': 'samples',
      'thigh': 'Thigh (0x68)',
      'shin': 'Shin (0x69)',
      'gyroscopeMagnitude': 'Gyro Angular Velocity (deg/s)',
      'sensorValidationFailed': 'Sensor Data Validation Issue',

      // Tutorial steps
      'tutorialTitle': 'Movement Technique Guide',
      'chairStandTutorialDesc':
          'Cross arms over chest. Stand up fully until knees extend, then sit back down completely.',
      'fastWalkTutorialDesc':
          'Walk at your maximum comfortable brisk pace for 20 metres without running.',
      'chairStandStep1': '1. Sit upright on chair with arms crossed over chest.',
      'chairStandStep2': '2. Stand up completely without using hands for support.',
      'chairStandStep3': '3. Sit down gently and repeat continuously for 30 seconds.',
      'fastWalkStep1': '1. Stand behind the starting line with sensors secured.',
      'fastWalkStep2': '2. Walk as quickly as is safe and comfortable.',
      'fastWalkStep3': '3. Walk past the 20-metre mark before turning or stopping.',
      'gotItStartTest': 'GOT IT, START TEST',

      // Results & AI
      'results': 'Results',
      'screeningResults': 'Screening Results',
      'movementAssessmentComplete': 'Movement assessment complete',
      'bothTestsRecorded':
          'Both movement tests have been recorded and analysed.',
      'viewScreeningResults': 'VIEW SCREENING RESULTS',
      'yourMovementAssessment': 'Your movement assessment',
      'recordedMovementProcessed':
          'The recorded movement data has been processed and combined with your assessment information.',
      'dataQuality': 'Data Quality',
      'testQuality': 'Test Quality',
      'dataQualityScore': 'Data Quality Score',
      'recordedSamples': 'Recorded samples',
      'recordingDuration': 'Recording duration',
      'sampleCoverage': 'Sample coverage',
      'timestampRegularity': 'Timestamp regularity',
      'sensorSignalQuality': 'Sensor signal quality',
      'movementPresence': 'Movement presence',
      'good': 'Good',
      'acceptable': 'Acceptable',
      'repeatRecommended': 'Repeat recommended',
      'technicalQualityExplanation':
          'This score describes the technical quality of the recorded sensor data.',
      'kneeMovement': 'Knee Joint Kinematics',
      'rangeOfMotion': 'Range of Motion (ROM)',
      'minimumAngle': 'Minimum angle',
      'maximumAngle': 'Maximum angle',
      'movementVariability': 'Movement variability',
      'repetitions': 'Repetitions',
      'averageCycle': 'Average cycle time',
      'walkDuration': 'Walk duration',
      'shinDynamicAcceleration': 'Shin dynamic acceleration',
      'aiAssistedScreening': 'AI-Assisted Preliminary Screening',
      'aiScreening': 'AI Risk Screening',
      'aiScreeningUnavailable': 'AI screening unavailable',
      'riskAssessment': 'Risk Assessment',
      'higherOARisk': 'Higher OA-associated risk indicated',
      'lowerOARisk': 'Lower OA-associated risk indicated',
      'modelEstimatedRisk': 'Model-estimated OA risk probability',
      'screeningThreshold': 'Screening threshold',
      'keyContributingFactors': 'Key contributing factors',
      'noRiskScoreGenerated': 'No artificial risk score has been generated.',
      'modelNotConnected':
          'A compatible trained AI model is not currently connected.',
      'clinicalInterpretation': 'Clinical Interpretation',
      'clinicalEvaluationRecommended':
          'Clinical evaluation is recommended for interpretation and follow-up.',
      'clinicalValidation': 'Clinical Validation Note',
      'clinicalValidationText':
          'Prototype screening results are for decision support and preliminary triage only.',
      'notClinicallyValidated':
          'The current prototype does not claim standalone diagnostic accuracy.',
      'notDiagnosis': 'AI Preliminary Screening • Not a Medical Diagnosis',
      'downloadReport': 'DOWNLOAD PDF REPORT',
      'generatingReport': 'Generating screening report...',
      'reportGenerated': 'Report generated successfully.',
      'reportError': 'Could not generate the report.',
      'invalidTestData': 'Test data invalid',
      'pleaseFinishCurrentTest':
          'Please finish or cancel the current test first.',
      'somethingWentWrong': 'Something went wrong.',
      'tryAgain': 'Please try again.',
      'liveSensorData': 'Live Sensor Data Stream',
      'acceleration': 'Accelerometer (g)',
      'gyroscope': 'Gyroscope (dps)',
    },

    'hi': {
      'appTitle': 'MedSync OA स्क्रीनिंग',
      'selectLanguage': 'भाषा चुनें',
      'language': 'भाषा',
      'movementHealth': 'डिजिटल घुटने के स्वास्थ्य की जांच',
      'understandKneeMovement': 'अपने घुटने की गति और जोड़ों का स्वास्थ्य समझें',
      'heroDescription':
          'लक्षणों और पहनने योग्य IMU सेंसर विश्लेषण को मिलाकर त्वरित डिजिटल स्क्रीनिंग।',
      'howItWorks': 'MedSync कैसे काम करता है',
      'tellUsHowYouFeel': '1. अपने लक्षण बताएं',
      'tellUsHowYouFeelDescription':
          'दर्द, जकड़न और दैनिक गतिविधियों से जुड़े सवालों के उत्तर दें।',
      'setUpMovementSensors': '2. मूवमेंट सेंसर सेट करें',
      'setUpMovementSensorsDescription':
          'MedSync KneeBand सेंसर कनेक्ट करें या डेमो मोड में शुरू करें।',
      'completeMovementTests': '3. मूवमेंट टेस्ट पूरा करें',
      'completeMovementTestsDescription':
          '30-सेकंड चेयर स्टैंड और 20 मीटर तेज चाल का परीक्षण करें।',
      'getAiAssessment': '4. AI जोखिम मूल्यांकन प्राप्त करें',
      'getAiAssessmentDescription':
          'त्वरित मूवमेंट विश्लेषण और स्क्रीनिंग रिपोर्ट प्राप्त करें।',
      'designedToSupport': 'नैदानिक सहायता के लिए डिज़ाइन किया गया',
      'supportDescription':
          'MedSync प्रारंभिक जांच के लिए वस्तुनिष्ठ डेटा प्रदान करता है।',
      'preliminaryDisclaimer':
          'MedSync केवल प्रारंभिक स्क्रीनिंग प्रदान करता है, यह डॉक्टरी निदान का विकल्प नहीं है।',
      'cancelScreening': 'स्क्रीनिंग रद्द करें',
      'step1Of4': 'चरण 1 / 4',
      'step2Of4': 'चरण 2 / 4',
      'step3Of4': 'चरण 3 / 4',
      'step4Of4': 'चरण 4 / 4',
      'continue': 'जारी रखें',
      'back': 'वापस',
      'next': 'आगे',
      'done': 'पूरा करें',
      'cancel': 'रद्द करें',
      'start': 'शुरू करें',
      'stop': 'रोकें',
      'retry': 'फिर प्रयास करें',
      'save': 'सहेजें',
      'close': 'बंद करें',
      'yes': 'हाँ',
      'no': 'नगण्य / कोई नहीं',
      'notAvailable': 'उपलब्ध नहीं',
      'patientAssessment': 'रोगी मूल्यांकन',
      'patientAssessmentTitle': 'अपने लक्षणों के बारे में बताएं',
      'patientAssessmentSubtitle':
          'इस जानकारी को सेंसर डेटा के साथ मिलाकर AI स्क्रीनिंग की जाती है।',
      'age': 'उम्र',
      'sex': 'लिंग',
      'female': 'महिला',
      'male': 'पुरुष',
      'preferNotToSay': 'बताना नहीं चाहते',
      'height': 'लंबाई',
      'weight': 'वजन',
      'bmi': 'BMI',
      'pain': 'दर्द',
      'stiffness': 'जकड़न',
      'functionalDifficulty': 'चलने-फिरने में कठिनाई',
      'activityRelatedPain': 'गतिविधि से संबंधित दर्द',
      'morningStiffness': 'सुबह की जकड़न',
      'enterAge': 'उम्र दर्ज करें',
      'enterHeight': 'लंबाई दर्ज करें',
      'enterWeight': 'वजन दर्ज करें',
      'selectSex': 'लिंग चुनें',
      'ratePain': 'दर्द का स्तर बताएं',
      'rateStiffness': 'जकड़न का स्तर बताएं',
      'rateDifficulty': 'कठिनाई का स्तर बताएं',
      'readyForScreening': 'स्क्रीनिंग के लिए तैयार?',
      'screeningIncludes': 'स्क्रीनिंग में चेयर स्टैंड और तेज चलने का टेस्ट शामिल है।',
      'startScreening': 'स्क्रीनिंग शुरू करें',
      'screeningComplete': 'स्क्रीनिंग पूरी हुई',
      'screeningDataCollected': 'स्क्रीनिंग डेटा एकत्रित',
      'sensorSetup': 'सेंसर सेटअप',
      'connectSensors': 'सेंसर कनेक्ट करें',
      'sensorConnection': 'सेंसर कनेक्शन',
      'connectToSensors': 'सेंसर कनेक्ट करें और टेस्ट शुरू करें।',
      'thighSensor': 'जांघ का सेंसर',
      'shinSensor': 'पिंडली का सेंसर',
      'connected': 'कनेक्टेड',
      'disconnected': 'डिस्कनेक्टेड',
      'searching': 'खोज रहे हैं...',
      'connecting': 'कनेक्ट हो रहा है...',
      'connectionSuccessful': 'सेंसर कनेक्शन सफल रहा।',
      'connectionFailed': 'सेंसर कनेक्शन विफल रहा।',
      'checkBluetooth': 'Bluetooth जांचें और सुनिश्चित करें कि सेंसर चालू हैं।',
      'chooseSensorSource': 'सेंसर स्रोत चुनें',
      'sensorSourceDescription': 'पहनने योग्य KneeBand सेंसर या डेमो मोड में से चुनें।',
      'demoMode': 'डेमो सिमुलेशन मोड',
      'demoModeSubtitle': 'सिम्युलेटेड IMU डेटा',
      'demoModeDescription': 'बिना हार्डवेयर के ऐप की सुविधाओं का परीक्षण करें।',
      'wearableMode': 'KneeBand BLE सेंसर',
      'wearableModeSubtitle': 'लाइव हार्डवेयर स्ट्रीमिंग',
      'wearableModeDescription': 'Bluetooth द्वारा KneeBand सेंसर से कनेक्ट करें।',
      'kneeBandConnection': 'KneeBand कनेक्शन',
      'connectKneeBand': 'KneeBand कनेक्ट करें',
      'kneeBandConnected': 'KneeBand कनेक्टेड',
      'wearableReadyMessage': 'सेंसर डेटा भेजने के लिए तैयार है।',
      'connectWearableMessage': 'सेंसर चालू करें और फ़ोन पर ब्लूटूथ चालू रखें।',
      'connectionStatus': 'कनेक्शन स्थिति',
      'wearableDevice': 'डिवाइस',
      'esp32PowerNotice': 'सुनिश्चित करें कि ESP32 KneeBand_OA नाम से चालू है।',
      'scanForDevices': 'डिवाइस खोजें',
      'availableDevices': 'उपलब्ध डिवाइस',
      'reconnect': 'पुनः कनेक्ट करें',
      'calibration': 'कैलिब्रेशन',
      'calibrating': 'कैलिब्रेशन हो रहा है...',
      'standStill': 'सेंसर कैलिब्रेट होने तक स्थिर खड़े रहें।',
      'calibrationComplete': 'कैलिब्रेशन पूरा हुआ।',
      'calibrationFailed': 'कैलिब्रेशन विफल रहा।',
      'keepStill': 'कैलिब्रेशन के दौरान स्थिर रहें।',
      'keepLegStillCalibration': 'सेंसर कैलिब्रेट होने तक 2 सेकंड के लिए पैर स्थिर रखें।',
      'movementAssessment': 'मूवमेंट मूल्यांकन',
      'movementTests': 'मूवमेंट टेस्ट',
      'chairStand': '30 सेकंड चेयर स्टैंड',
      'fastWalk': 'तेज चाल',
      'fastWalk20m': '20 मीटर तेज चाल',
      'chairStandInstruction': 'कुर्सी पर बैठें और 30 सेकंड तक लगातार खड़े हों और बैठें।',
      'fastWalkInstruction': '20 मीटर तक सुरक्षित तरीके से तेज चलें।',
      'sitStandRepeatedly': '30 सेकंड तक लगातार खड़े हों और बैठें।',
      'walkQuickly': '20 मीटर तक सुरक्षित तरीके से तेज चलें।',
      'keepSensorsSecure': 'शुरू करने से पहले जांचें कि दोनों सेंसर बंधे हैं।',
      'followInstructions': 'स्क्रीन पर दिए गए निर्देशों का पालन करें।',
      'safetyFirst': 'तेज दर्द या चक्कर आने पर टेस्ट तुरंत रोक दें।',
      'getReady': 'तैयार हो जाएं',
      'testRunning': 'टेस्ट चल रहा है',
      'testCompleted': 'टेस्ट पूरा हुआ',
      'testFailed': 'टेस्ट विफल',
      'ready': 'तैयार',
      'samplesCollected': 'सैंपल',
      'duration': 'अवधि',
      'samplingRate': 'सैंपलिंग दर',
      'startTest': 'टेस्ट शुरू करें',
      'stopTest': 'टेस्ट रोकें',
      'watchTutorial': 'ट्यूटोरियल देखें',
      'tutorial': 'एनिमेटेड ट्यूटोरियल',
      'howToPerform': 'यह टेस्ट कैसे करें',
      'sensorData': 'लाइव मूवमेंट डेटा',
      'sensorsReady': 'सेंसर कैलिब्रेट हो चुके हैं।',
      'positionAndPrepare': 'स्थान लें और शुरू करने के लिए तैयार रहें।',
      'continueMovement': 'लगातार और स्थिर गति बनाए रखें।',
      'points': 'सैंपल',
      'thigh': 'जांघ',
      'shin': 'पिंडली',
      'gyroscopeMagnitude': 'जायरोस्कोप गति (deg/s)',
      'sensorValidationFailed': 'सेंसर डेटा अमान्य है',
      'tutorialTitle': 'मूवमेंट तकनीक गाइड',
      'chairStandTutorialDesc':
          'हाथों को छाती पर रखें। पूरी तरह खड़े हों और फिर बैठें।',
      'fastWalkTutorialDesc': 'बिना दौड़े 20 मीटर तक अपनी सामान्य तेज गति से चलें।',
      'chairStandStep1': '1. कुर्सी पर सीधे बैठें और हाथ छाती पर रखें।',
      'chairStandStep2': '2. बिना हाथों का सहारा लिए पूरी तरह सीधे खड़े हों।',
      'chairStandStep3': '3. आराम से बैठें और 30 सेकंड तक दोहराएं।',
      'fastWalkStep1': '1. शुरुआत की रेखा पर खड़े हो जाएं।',
      'fastWalkStep2': '2. जितनी जल्दी हो सके सुरक्षित रूप से चलें।',
      'fastWalkStep3': '3. 20 मीटर की रेखा पार करके ही रुकें।',
      'gotItStartTest': 'समझ गया, टेस्ट शुरू करें',
      'results': 'परिणाम',
      'screeningResults': 'स्क्रीनिंग परिणाम',
      'movementAssessmentComplete': 'मूवमेंट मूल्यांकन पूरा हुआ',
      'bothTestsRecorded': 'दोनों मूवमेंट टेस्ट रिकॉर्ड और विश्लेषित किए गए।',
      'viewScreeningResults': 'स्क्रीनिंग परिणाम देखें',
      'yourMovementAssessment': 'आपका मूवमेंट मूल्यांकन',
      'recordedMovementProcessed': 'रिकॉर्ड किए गए डेटा का विश्लेषण किया गया है।',
      'dataQuality': 'डेटा गुणवत्ता',
      'testQuality': 'टेस्ट गुणवत्ता',
      'dataQualityScore': 'डेटा गुणवत्ता स्कोर',
      'recordedSamples': 'सैंपल',
      'recordingDuration': 'रिकॉर्डिंग अवधि',
      'sampleCoverage': 'कवरेज',
      'timestampRegularity': 'नियमितता',
      'sensorSignalQuality': 'सिग्नल गुणवत्ता',
      'movementPresence': 'मूवमेंट',
      'good': 'उत्कृष्ट',
      'acceptable': 'स्वीकार्य',
      'repeatRecommended': 'दोबारा टेस्ट की सलाह',
      'technicalQualityExplanation': 'यह स्कोर सेंसर डेटा की तकनीकी गुणवत्ता दर्शाता है।',
      'kneeMovement': 'घुटने की गति',
      'rangeOfMotion': 'गति की सीमा (ROM)',
      'minimumAngle': 'न्यूनतम कोण',
      'maximumAngle': 'अधिकतम कोण',
      'movementVariability': 'परिवर्तनशीलता',
      'repetitions': 'दोहराव',
      'averageCycle': 'औसत चक्र समय',
      'walkDuration': 'चलने की अवधि',
      'shinDynamicAcceleration': 'पिंडली का एक्सेलेरेशन',
      'aiAssistedScreening': 'AI-सहायित प्रारंभिक स्क्रीनिंग',
      'aiScreening': 'AI जोखिम स्क्रीनिंग',
      'aiScreeningUnavailable': 'AI स्क्रीनिंग उपलब्ध नहीं',
      'riskAssessment': 'जोखिम मूल्यांकन',
      'higherOARisk': 'उच्च जोखिम का संकेत',
      'lowerOARisk': 'कम जोखिम का संकेत',
      'modelEstimatedRisk': 'अनुमानित जोखिम संभावना',
      'screeningThreshold': 'स्क्रीनिंग सीमा',
      'keyContributingFactors': 'मुख्य कारक',
      'noRiskScoreGenerated': 'कोई जोखिम स्कोर उत्पन्न नहीं किया गया।',
      'modelNotConnected': 'AI मॉडल कनेक्ट नहीं है।',
      'clinicalInterpretation': 'क्लिनिकल व्याख्या',
      'clinicalEvaluationRecommended': 'डॉक्टरी सलाह की सिफारिश की जाती है।',
      'clinicalValidation': 'क्लिनिकल नोट',
      'clinicalValidationText': 'यह परिणाम केवल प्रारंभिक स्क्रीनिंग और सहायता के लिए है।',
      'notClinicallyValidated': 'यह मेडिकल निदान का दावा नहीं करता।',
      'notDiagnosis': 'AI प्रारंभिक स्क्रीनिंग • डॉक्टरी निदान नहीं',
      'downloadReport': 'PDF रिपोर्ट डाउनलोड करें',
      'generatingReport': 'रिपोर्ट तैयार हो रही है...',
      'reportGenerated': 'रिपोर्ट तैयार हो गई।',
      'reportError': 'रिपोर्ट तैयार नहीं हो सकी।',
      'invalidTestData': 'डेटा अमान्य है',
      'pleaseFinishCurrentTest': 'कृपया पहले वर्तमान टेस्ट पूरा करें।',
      'somethingWentWrong': 'कुछ गलत हो गया।',
      'tryAgain': 'कृपया पुनः प्रयास करें।',
      'liveSensorData': 'लाइव सेंसर डेटा',
      'acceleration': 'एक्सेलेरोमीटर',
      'gyroscope': 'जायरोस्कोप',
    },

    'as': {
      'appTitle': 'MedSync OA স্ক্ৰীনিং',
      'selectLanguage': 'ভাষা বাছক',
      'language': 'ভাষা',
      'movementHealth': 'ডিজিটেল আঁঠুৰ স্বাস্থ্য পৰীক্ষা',
      'understandKneeMovement': 'আপোনাৰ আঁঠুৰ চলাচল আৰু স্বাস্থ্য বুজি পাওক',
      'heroDescription':
          'লক্ষণসমূহ আৰু পিন্ধিব পৰা IMU চেন্সৰ সংমিশ্ৰণেৰে খৰতকীয়া ডিজিটেল স্ক্ৰীনিং।',
      'howItWorks': 'MedSync কেনেকৈ কাম কৰে',
      'tellUsHowYouFeel': '১. লক্ষণসমূহ কওক',
      'tellUsHowYouFeelDescription': 'আঁঠুৰ বিষ, টান ভাব আৰু দৈনিক চলাচলৰ উত্তৰ দিয়ক।',
      'setUpMovementSensors': '২. চেন্সৰ সংযোগ কৰক',
      'setUpMovementSensorsDescription': 'KneeBand চেন্সৰ ব্লুটুথৰ দ্বাৰা সংযোগ কৰক।',
      'completeMovementTests': '৩. পৰীক্ষা সম্পূৰ্ণ কৰক',
      'completeMovementTestsDescription': '৩০ ছেকেণ্ডৰ চকী পৰীক্ষা আৰু ২০ মিটাৰ খোজ কঢ়া।',
      'getAiAssessment': '৪. AI মূল্যায়ন প্ৰাপ্ত কৰক',
      'getAiAssessmentDescription': 'মুহূৰ্ততে স্ক্ৰীনিং ৰিপ’ৰ্ট লাভ কৰক।',
      'designedToSupport': 'চিকিৎসকীয় সহায়ৰ বাবে প্ৰস্তুত',
      'supportDescription': 'প্ৰাৰম্ভিক স্ক্ৰীনিং সহজ কৰাৰ বাবে ডাটা প্ৰদান কৰে।',
      'preliminaryDisclaimer': 'MedSync কেবল প্ৰাৰম্ভিক স্ক্ৰীনিং, কোনো ৰোগ নিৰ্ণয় নহয়।',
      'cancelScreening': 'ৰোগ নিৰ্ণয় বাতিল কৰক',
      'step1Of4': 'পৰ্যায় ১ / ৪',
      'step2Of4': 'পৰ্যায় ২ / ৪',
      'step3Of4': 'পৰ্যায় ৩ / ৪',
      'step4Of4': 'পৰ্যায় ৪ / ৪',
      'continue': 'আগবাঢ়ক',
      'back': 'উভতি যাওক',
      'next': 'পৰৱৰ্তী',
      'done': 'সম্পূৰ্ণ',
      'cancel': 'বাতিল কৰক',
      'start': 'আৰম্ভ কৰক',
      'stop': 'ৰখাঅ’ক',
      'retry': 'পুনৰ চেষ্টা কৰক',
      'save': 'সংৰক্ষণ কৰক',
      'close': 'বন্ধ কৰক',
      'yes': 'হয়',
      'no': 'নাই / বিষ নাই',
      'notAvailable': 'উপলব্ধ নহয়',
      'patientAssessment': 'ৰোগীৰ মূল্যায়ন',
      'patientAssessmentTitle': 'আপোনাৰ লক্ষণসমূহ কওক',
      'patientAssessmentSubtitle': 'এই তথ্যসমূহ চেন্সৰ ডাটাৰ সৈতে মিলাই মূল্যায়ন কৰা হয়।',
      'age': 'বয়স',
      'sex': 'লিংগ',
      'female': 'মহিলা',
      'male': 'পুৰুষ',
      'preferNotToSay': 'ক’বলৈ নিবিচাৰো',
      'height': 'উচ্চতা',
      'weight': 'ওজন',
      'bmi': 'BMI',
      'pain': 'বিষ',
      'stiffness': 'টান ভাব',
      'functionalDifficulty': 'চলাচলত অসুবিধা',
      'activityRelatedPain': 'কাম কৰোতে বিষ',
      'morningStiffness': 'পুৱাৰ টান ভাব',
      'enterAge': 'বয়স দিয়ক',
      'enterHeight': 'উচ্চতা দিয়ক (ছেমি)',
      'enterWeight': 'ওজন দিয়ক (কিগ্ৰা)',
      'selectSex': 'লিংগ বাছক',
      'ratePain': 'বিষৰ মাত্ৰা দিয়ক (০ - ১০)',
      'rateStiffness': 'টান ভাবৰ মাত্ৰা দিয়ক (০ - ১০)',
      'rateDifficulty': 'অসুবিধাৰ মাত্ৰা দিয়ক (০ - ১০)',
      'startScreening': 'স্ক্ৰীনিং আৰম্ভ কৰক',
      'screeningIncludes': 'চকী পৰীক্ষা আৰু খোজ কঢ়া পৰীক্ষা অন্তর্ভুক্ত।',
      'sensorSetup': 'চেন্সৰ ছেটআপ',
      'connectSensors': 'চেন্সৰ সংযোগ কৰক',
      'thighSensor': 'ৰানৰ চেন্সৰ',
      'shinSensor': 'নলী ভৰিৰ চেন্সৰ',
      'connected': 'সংযুক্ত',
      'disconnected': 'বিচ্ছিন্ন',
      'chairStand': '৩০ ছেকেণ্ডৰ চকী পৰীক্ষা',
      'fastWalk': 'খৰতকীয়া খোজ',
      'fastWalk20m': '২০ মিটাৰ খৰতকীয়া খোজ',
      'chairStandInstruction': 'চকীত বহি ৩০ ছেকেণ্ডৰ বাবে থিয় হ’ব আৰু বহিব।',
      'fastWalkInstruction': '২০ মিটাৰ খৰতকীয়াকৈ খোজ কাঢ়ক।',
      'getReady': 'প্ৰস্তুত হওক',
      'testRunning': 'পৰীক্ষা চলি আছে',
      'testCompleted': 'পৰীক্ষা সম্পূৰ্ণ হ’ল',
      'startTest': 'পৰীক্ষা আৰম্ভ কৰক',
      'stopTest': 'পৰীক্ষা বন্ধ কৰক',
      'watchTutorial': 'টিউটৰিয়েল চাওক',
      'results': 'ফলাফল',
      'screeningResults': 'স্ক্ৰীনিং ফলাফল',
      'higherOARisk': 'অধিক বিপদাশংকা',
      'notDiagnosis': 'AI স্ক্ৰীনিং • চিকিৎসা নিদান নহয়',
      'downloadReport': 'ৰিপ’ৰ্ট ডাউনলোড কৰক',
      'gotItStartTest': 'বুজি পালোঁ, আৰম্ভ কৰক',
    },

    'bn': {
      'appTitle': 'MedSync OA স্ক্রিনিং',
      'selectLanguage': 'ভাষা নির্বাচন করুন',
      'language': 'ভাষা',
      'movementHealth': 'ডিজিটাল হাঁটুর স্বাস্থ্য পরীক্ষা',
      'understandKneeMovement': 'আপনার হাঁটুর সঞ্চালন ও জয়েন্টের স্বাস্থ্য বুঝুন',
      'heroDescription':
          'উপসর্গ এবং পরিধেয় IMU সেন্সরের সাহায্যে দ্রুত ডিজিটাল স্ক্রিনিং।',
      'howItWorks': 'MedSync যেভাবে কাজ করে',
      'tellUsHowYouFeel': '১. আপনার লক্ষণ জানান',
      'tellUsHowYouFeelDescription': 'হাঁটুর ব্যথা ও নড়াচড়ার সমস্যা সম্পর্কে উত্তর দিন।',
      'setUpMovementSensors': '২. সেন্সর যুক্ত করুন',
      'setUpMovementSensorsDescription': 'KneeBand সেন্সর ব্লুটুথের মাধ্যমে যুক্ত করুন।',
      'completeMovementTests': '৩. টেস্ট সম্পূর্ণ করুন',
      'completeMovementTestsDescription': '৩০ সেকেন্ডের চেয়ার টেস্ট এবং ২০ মিটার হাঁটা।',
      'getAiAssessment': '৪. AI মূল্যায়ন পান',
      'getAiAssessmentDescription': 'তাৎক্ষণিক ফলাফল ও রিপোর্ট পান।',
      'designedToSupport': 'চিকিৎসকদের সহায়তার জন্য তৈরি',
      'supportDescription': 'প্রাথমিক স্ক্রিনিং এর জন্য নিখুঁত তথ্য প্রদান করে।',
      'preliminaryDisclaimer': 'এটি প্রাথমিক পরীক্ষা, সরাসরি ডাক্তারের পরামর্শের বিকল্প নয়।',
      'cancelScreening': 'বাতিল করুন',
      'step1Of4': 'ধাপ ১ / ৪',
      'step2Of4': 'ধাপ ২ / ৪',
      'step3Of4': 'ধাপ ৩ / ৪',
      'step4Of4': 'ধাপ ৪ / ৪',
      'continue': 'এগিয়ে যান',
      'back': 'ফিরে যান',
      'next': 'পরবর্তী',
      'done': 'সম্পন্ন',
      'cancel': 'বাতিল',
      'start': 'শুরু করুন',
      'stop': 'থামুন',
      'retry': 'পুনরায় চেষ্টা করুন',
      'save': 'সংরক্ষণ করুন',
      'close': 'বন্ধ করুন',
      'yes': 'হ্যাঁ',
      'no': 'নেই / ব্যথা নেই',
      'notAvailable': 'উপলব্ধ নয়',
      'patientAssessment': 'রোগীর মূল্যায়ন',
      'patientAssessmentTitle': 'আপনার লক্ষণ সম্পর্কে জানান',
      'patientAssessmentSubtitle': 'এই তথ্য সেন্সর তথ্যের সাথে মিলিয়ে মূল্যায়ন করা হয়।',
      'age': 'বয়স',
      'sex': 'লিঙ্গ',
      'female': 'মহিলা',
      'male': 'পুরুষ',
      'preferNotToSay': 'বলতে ইচ্ছুক নই',
      'height': 'উচ্চতা',
      'weight': 'ওজন',
      'bmi': 'BMI',
      'pain': 'ব্যথা',
      'stiffness': 'আড়ষ্টতা',
      'functionalDifficulty': 'নড়াচড়ায় অসুবিধা',
      'activityRelatedPain': 'কাজের সময় ব্যথা',
      'morningStiffness': 'সকালের আড়ষ্টতা',
      'enterAge': 'বয়স লিখুন',
      'enterHeight': 'উচ্চতা লিখুন (সেমি)',
      'enterWeight': 'ওজন লিখুন (কেজি)',
      'selectSex': 'লিঙ্গ নির্বাচন করুন',
      'ratePain': 'ব্যথার মাত্রা দিন (০ - ১০)',
      'rateStiffness': 'আড়ষ্টতার মাত্রা দিন (০ - ১০)',
      'rateDifficulty': 'অসুবিধার মাত্রা দিন (০ - ১০)',
      'startScreening': 'স্ক্রিনিং শুরু করুন',
      'screeningIncludes': 'চেয়ার টেস্ট এবং হাঁটার টেস্ট অন্তর্ভুক্ত।',
      'sensorSetup': 'সেন্সর সেটআপ',
      'connectSensors': 'সেন্সর সংযোগ করুন',
      'thighSensor': 'রানের সেন্সর',
      'shinSensor': 'পায়ের নলীর সেন্সর',
      'connected': 'সংযুক্ত',
      'disconnected': 'বিচ্ছিন্ন',
      'chairStand': '৩০ সেকেন্ডের চেয়ার টেস্ট',
      'fastWalk': 'দ্রুত হাঁটা',
      'fastWalk20m': '২০ মিটার দ্রুত হাঁটা',
      'chairStandInstruction': 'চেয়ারে বসে ৩০ সেকেন্ড বারবার দাঁড়ান এবং বসুন।',
      'fastWalkInstruction': '২০ মিটার দ্রুত ও নিরাপদে হাঁটুন।',
      'getReady': 'প্রস্তুত হন',
      'testRunning': 'টেস্ট চলছে',
      'testCompleted': 'টেস্ট সম্পন্ন',
      'startTest': 'টেস্ট শুরু করুন',
      'stopTest': 'টেস্ট থামান',
      'watchTutorial': 'টিউটোরিয়াল দেখুন',
      'results': 'ফলাফল',
      'screeningResults': 'স্ক্রিনিং ফলাফল',
      'higherOARisk': 'উচ্চ ঝুঁকির ইঙ্গিত',
      'notDiagnosis': 'AI স্ক্রিনিং • এটি চিকিৎসা পরামর্শ নয়',
      'downloadReport': 'রিপোর্ট ডাউনলোড করুন',
      'gotItStartTest': 'বুঝেছি, টেস্ট শুরু করুন',
    },

    'mni': {
      'appTitle': 'MedSync OA স্ক্রীনিং',
      'selectLanguage': 'লোন খনবিয়ু',
      'language': 'লোন',
      'movementHealth': 'খুউক কী চত-থোক স্বাস্থ্য় চাংয়েংবা',
      'understandKneeMovement': 'নহাঙ্কী খুউককী চত-থোক অমসুং হকচাং খঙবিয়ু',
      'heroDescription':
          'আই-এম-য়ু সেন্সরগা লোইননা খুউককী চত-থোক চাংয়েংবা।',
      'howItWorks': 'MedSync না কাম তৌরিবা মওং',
      'tellUsHowYouFeel': '১. অনাবগী মওং হায়বিয়ু',
      'tellUsHowYouFeelDescription': 'খুউক অনাবা অমসুং চত-থোক চৎপগী ৱাহং অনৌবা পাখনবিয়ু।',
      'setUpMovementSensors': '২. সেন্সর শিনবিয়ু',
      'setUpMovementSensorsDescription': 'KneeBand সেন্সর ব্লুটুথগা শিনবিয়ু।',
      'completeMovementTests': '৩. চত-থোক চাংয়েংবা সম্পূর্ণ তৌবিয়ু',
      'completeMovementTestsDescription': '৩০ সেকেন্ড ফম্পাক অমসুং ২০ মিটার চতপা চাংয়েংবা।',
      'getAiAssessment': '৪. এ-আই রিপোর্ত লৌবিয়ু',
      'getAiAssessmentDescription': 'মতুং ইনবা এ-আই রিপোর্ত লৌবিয়ু।',
      'cancelScreening': 'চাংয়েংবা লেপবিয়ু',
      'step1Of4': 'খোংথাং ১ / ৪',
      'step2Of4': 'খোংথাং ২ / ৪',
      'step3Of4': 'খোংথাং ৩ / ৪',
      'step4Of4': 'खोংথাং ৪ / ৪',
      'continue': 'মখা তাইবিয়ু',
      'back': 'হনবিয়ু',
      'next': 'মথং',
      'done': 'লোইরে',
      'cancel': 'কাখায়বিয়ু',
      'start': 'হৌবিয়ু',
      'stop': 'লেপবিয়ু',
      'patientAssessment': 'অনাবগী চাংয়েংবা',
      'patientAssessmentTitle': 'নহাঙ্কী অনাবগী মওং হায়বিয়ু',
      'patientAssessmentSubtitle': 'মসিগী পাউ অসি চত-থোক ডাতাগা লোইননা এ-আই চাংয়েং তৌবদা শীজিন্নই।',
      'age': 'চহি',
      'sex': 'নুপা/নুপী',
      'female': 'নুপী',
      'male': 'নুপা',
      'preferNotToSay': 'হায়নিংদে',
      'height': 'অৱাংবা',
      'weight': 'অরুম্বা',
      'bmi': 'BMI',
      'pain': 'অনাবা',
      'stiffness': 'কন্হৌবা',
      'functionalDifficulty': 'চত-থোক অৱাবা',
      'activityRelatedPain': 'থবক-থৌরম তৌবদা অনাবা',
      'morningStiffness': 'অয়ুকত কন্হৌবা',
      'enterAge': 'চহি ইবিয়ু',
      'enterHeight': 'অৱাংবা ইবিয়ু (cm)',
      'enterWeight': 'অরুম্বা ইবিয়ু (kg)',
      'selectSex': 'নুপা/নুপী খনবিয়ু',
      'ratePain': 'অনাবগী চাং ইবিয়ু (০ - ১০)',
      'rateStiffness': 'কন্হৌবগী চাং ইবিয়ু (০ - ১০)',
      'rateDifficulty': 'অৱাবগী চাং ইবিয়ু (০ - ১০)',
      'startScreening': 'স্ক্রীনিং হৌবিয়ু',
      'sensorSetup': 'সেন্সর সেত্তপ',
      'chairStand': '৩০ সেকেন্ড ফম্পাক চাংয়েংবা',
      'fastWalk': 'য়াংনা চতপা',
      'fastWalk20m': '২০ মিটার য়াংনা চতপা',
      'no': 'অনাবা লৈতে',
      'higherOARisk': 'অৱাংবা কাংলোনগী অনাবা',
      'notDiagnosis': 'এ-আই চাংয়েংবা • লাইয়েংবা নত্তে',
      'watchTutorial': 'তম্বীবা য়েংবিয়ু',
      'results': 'ফলফল',
      'screeningResults': 'স্ক্ৰীনিং ফলফল',
      'downloadReport': 'রিপোর্ত লৌরৌ',
      'gotItStartTest': 'খঙরে, হৌবিয়ু',
    },

    'kha': {
      'appTitle': 'MedSync OA Screening',
      'selectLanguage': 'Jied iaka Ktien',
      'language': 'Ktien',
      'movementHealth': 'Ka jingkhein bniah iaki khohsiew',
      'understandKneeMovement': 'Sngewthuh ia ka jingkhih bad jingkoit khohsiew',
      'heroDescription':
          'Jingscreening iaki dak jingshitom bad ka jingkhih lyngba ki sensor.',
      'howItWorks': 'Kumno ka MedSync ka treikam',
      'tellUsHowYouFeel': '1. Iathuh iaki dak jingshitom',
      'tellUsHowYouFeelDescription': 'Jingkylli halor ka jingpang khohsiew bad jingeh baiad.',
      'setUpMovementSensors': '2. Pyniasoh iaki Sensor',
      'setUpMovementSensorsDescription': 'Pyniasoh ia ki KneeBand Bluetooth sensor.',
      'completeMovementTests': '3. Pyndep iaka Jingkynjih',
      'completeMovementTestsDescription': 'Pyndep ia ka test shong-ieng 30s bad iaid 20m.',
      'getAiAssessment': '4. Yoh iaka report na ka AI',
      'getAiAssessmentDescription': 'Yoh ia ka report kaba pura wut wut.',
      'cancelScreening': 'Pynduh ka Screening',
      'step1Of4': 'Jingkieng 1 naf 4',
      'step2Of4': 'Jingkieng 2 naf 4',
      'step3Of4': 'Jingkieng 3 naf 4',
      'step4Of4': 'Jingkieng 4 naf 4',
      'continue': 'BTENG',
      'back': 'DIN',
      'next': 'NGAI',
      'done': 'DEP',
      'cancel': 'PYNDUH',
      'start': 'SDANG',
      'stop': 'SANGEH',
      'patientAssessment': 'Jingkhein briew pang',
      'patientAssessmentTitle': 'Iathuh iaki dak jingshitom jong phi',
      'patientAssessmentSubtitle': 'Ying pyndonkam ia kine ki jingtip mar bad ki sensor data.',
      'age': 'Rta',
      'sex': 'Kynthei/Shynrang',
      'female': 'Kynthei',
      'male': 'Shynrang',
      'preferNotToSay': 'Kym thoh',
      'height': 'Jingjrong',
      'weight': 'Jingkhia',
      'pain': 'Jingpang',
      'stiffness': 'Jingeh',
      'functionalDifficulty': 'Jingeh baid-iaid',
      'activityRelatedPain': 'Jingpang haba leh kam',
      'morningStiffness': 'Jingeh mynstep',
      'enterAge': 'Thoh rta',
      'enterHeight': 'Thoh jingjrong (cm)',
      'enterWeight': 'Thoh jingkhia (kg)',
      'selectSex': 'Jied Kynthei/Shynrang',
      'ratePain': 'Bishar jingpang (0 - 10)',
      'rateStiffness': 'Bishar jingeh (0 - 10)',
      'rateDifficulty': 'Bishar jingeh iaid (0 - 10)',
      'startScreening': 'Sdang ka Screening',
      'sensorSetup': 'Pynkhreh Sensor',
      'chairStand': '30-Second Shong bad Ieng',
      'fastWalk': 'Iaid stet 20 metre',
      'fastWalk20m': 'Iaid stet 20m',
      'no': 'Em / Ym don',
      'higherOARisk': 'Jingma ba khraw',
      'notDiagnosis': 'AI Screening • Ym dei ka jingpynkhiah doctor',
      'watchTutorial': 'Pule/Peit ka rukom leh',
      'results': 'Ka Jingoh',
      'screeningResults': 'Jingoh Screening',
      'downloadReport': 'Hiar ia ka Report',
      'gotItStartTest': 'Sngewthuh, Sdang noh',
    },

    'lus': {
      'appTitle': 'MedSync OA Screening',
      'selectLanguage': 'Tawng Thlang Ropwh',
      'language': 'Tawng',
      'movementHealth': 'Kup Kal Phung Endikna',
      'understandKneeMovement': 'I kup chet vel dan leh hriselna hrethiam rawh',
      'heroDescription': 'Kup tinainate leh chetvelna sensor hmanga endikna.',
      'howItWorks': 'MedSync Hnathawh Dan',
      'tellUsHowYouFeel': '1. I natna te hrilh rawh',
      'tellUsHowYouFeelDescription': 'Kup na leh chet harsa zawhna te chhang rawh.',
      'setUpMovementSensors': '2. Sensor Samboom Rawh',
      'setUpMovementSensorsDescription': 'KneeBand Bluetooth sensor zawm rawh.',
      'completeMovementTests': '3. Chetvel Unee Phak Rawh',
      'completeMovementTestsDescription': 'Sekand 30 thut-din leh meter 20 kal zawh rawh.',
      'getAiAssessment': '4. AI Report La Rawh',
      'getAiAssessmentDescription': 'AI report kimchang tak la vat rawh.',
      'cancelScreening': 'Screening Sut Rawh',
      'step1Of4': 'Thawh 1-na',
      'step2Of4': 'Thawh 2-na',
      'step3Of4': 'Thawh 3-na',
      'step4Of4': 'Thawh 4-na',
      'continue': 'KAL ZEL RAWH',
      'back': 'KIR RAWH',
      'next': 'A DAWT',
      'done': 'ZO TA',
      'cancel': 'TIH TAWP',
      'start': 'BUL TAN RAWH',
      'stop': 'TOP RAWH',
      'patientAssessment': 'Mina Endikna',
      'patientAssessmentTitle': 'I kup nat dan te hrilh rawh',
      'patientAssessmentSubtitle': 'Heng thukah te hi sensor data nen pawlh in a endik ang.',
      'age': 'Kum',
      'sex': 'Hmeichhia/Mipa',
      'female': 'Hmeichhia',
      'male': 'Mipa',
      'preferNotToSay': 'Hrilh duh lo',
      'height': 'Sang',
      'weight': 'Rih zawng',
      'pain': 'Na',
      'stiffness': 'Khawng',
      'functionalDifficulty': 'Kal harsatna',
      'activityRelatedPain': 'Thawh laia na',
      'morningStiffness': 'Zing khawngna',
      'enterAge': 'Kum chhut rawh',
      'enterHeight': 'San zawng chhut (cm)',
      'enterWeight': 'Rih zawng chhut (kg)',
      'selectSex': 'Hmeichhia/Mipa thlang rawh',
      'ratePain': 'Na bik zat chhut (0 - 10)',
      'rateStiffness': 'Khawng zat chhut (0 - 10)',
      'rateDifficulty': 'Harsatna zat chhut (0 - 10)',
      'startScreening': 'Screening Tan Rawh',
      'sensorSetup': 'Sensor Ruahmanna',
      'chairStand': 'Sekand 30 Thut leh Din',
      'fastWalk': 'Chak taka kal 20m',
      'fastWalk20m': 'Meter 20 Chak Taka Kal',
      'no': 'Aih / Na lo',
      'higherOARisk': 'Risk Sang',
      'notDiagnosis': 'AI Endikna • Doctor Enna a ni lo',
      'watchTutorial': 'Zirtirna en rawh',
      'results': 'Rilru Chhuahna',
      'screeningResults': 'Endikna Result',
      'downloadReport': 'Report La Rawh',
      'gotItStartTest': 'Ka hrethiam e, Tan rawh',
    },

    'ne': {
      'appTitle': 'MedSync OA स्क्रिनिङ',
      'selectLanguage': 'भाषा छान्नुहोस्',
      'language': 'भाषा',
      'movementHealth': 'डिजिटल घुँडाको स्वास्थ्य जाँच',
      'understandKneeMovement': 'आफ्नो घुँडाको चाल र जोडनीको स्वास्थ्य बुझ्नुहोस्',
      'heroDescription':
          'लक्षणहरू र सेन्सर गति विश्लेषणको प्रयोग गरी द्रुत डिजिटल स्क्रिनिङ।',
      'howItWorks': 'MedSync कसरी काम गर्छ',
      'tellUsHowYouFeel': '१. आफ्ना लक्षणहरू भन्नुहोस्',
      'tellUsHowYouFeelDescription': 'घुँडाको दुखाइ र कडापनको बारेमा उत्तर दिनुहोस्।',
      'setUpMovementSensors': '२. सेन्सर जोड्नुहोस्',
      'setUpMovementSensorsDescription': 'KneeBand सेन्सर ब्लुटुथबाट कनेक्ट गर्नुहोस्।',
      'completeMovementTests': '३. गति परीक्षण पूरा गर्नुहोस्',
      'completeMovementTestsDescription': '३० सेकेन्ड कुर्सी परीक्षण र २० मिटर छिटो हिँडाइ।',
      'getAiAssessment': '४. AI मूल्याङ्कन प्राप्त गर्नुहोस्',
      'getAiAssessmentDescription': 'तत्काल स्क्रिनिङ रिपोर्ट प्राप्त गर्नुहोस्।',
      'cancelScreening': 'स्क्रिनिङ रद्द गर्नुहोस्',
      'step1Of4': 'चरण १ / ४',
      'step2Of4': 'चरण २ / ४',
      'step3Of4': 'चरण ३ / ४',
      'step4Of4': 'चरण ४ / ४',
      'continue': 'जारी राख्नुहोस्',
      'back': 'फर्कनुहोस्',
      'next': 'अर्को',
      'done': 'सम्पन्न',
      'cancel': 'रद्द गर्नुहोस्',
      'start': 'शुरू गर्नुहोस्',
      'stop': 'रोक्नुहोस्',
      'retry': 'पुनः प्रयास गर्नुहोस्',
      'save': 'बचत गर्नुहोस्',
      'close': 'बन्द गर्नुहोस्',
      'yes': 'हो',
      'no': 'छैन / दुखाइ छैन',
      'notAvailable': 'उपलब्ध छैन',
      'patientAssessment': 'बिरामी मूल्याङ्कन',
      'patientAssessmentTitle': 'आफ्ना लक्षणहरू बारे भन्नुहोस्',
      'patientAssessmentSubtitle': 'यो जानकारी सेन्सर गति डेटासँग मिलाएर विश्लेषण गरिन्छ।',
      'age': 'उमेर',
      'sex': 'लिङ्ग',
      'female': 'महिला',
      'male': 'पुरुष',
      'preferNotToSay': 'भन्न चाहन्न',
      'height': 'उचाइ',
      'weight': 'तौल',
      'bmi': 'BMI',
      'pain': 'दुखाइ',
      'stiffness': 'कडापन',
      'functionalDifficulty': 'चालमा कठिनाइ',
      'activityRelatedPain': 'काम गर्दा हुने दुखाइ',
      'morningStiffness': 'बिहानको कडापन',
      'enterAge': 'उमेर लेख्नुहोस्',
      'enterHeight': 'उचाइ लेख्नुहोस् (सेमी)',
      'enterWeight': 'तौल लेख्नुहोस् (किग्रा)',
      'selectSex': 'लिङ्ग छान्नुहोस्',
      'ratePain': 'दुखाइको मात्रा छान्नुहोस् (० - १०)',
      'rateStiffness': 'कडापनको मात्रा छान्नुहोस् (० - १०)',
      'rateDifficulty': 'कठिनाइको मात्रा छान्नुहोस् (० - १०)',
      'startScreening': 'स्क्रिनिङ शुरू गर्नुहोस्',
      'screeningIncludes': 'कुर्सी परीक्षण र छिटो हिँडाइ समावेश छ।',
      'sensorSetup': 'सेन्सर सेटअप',
      'connectSensors': 'सेन्सर जोड्नुहोस्',
      'thighSensor': 'जाँघको सेन्सर',
      'shinSensor': 'पिँडुलाको सेन्सर',
      'connected': 'कनेक्ट भयो',
      'disconnected': 'डिस्कनेक्ट भयो',
      'chairStand': '३० सेकेन्ड कुर्सी परीक्षण',
      'fastWalk': 'छिटो हिँडाइ',
      'fastWalk20m': '२० मिटर छिटो हिँडाइ',
      'chairStandInstruction': 'कुर्सीमा बसेर ३० सेकेन्डसम्म लगातार उभिनुहोस् र बस्नुहोस्।',
      'fastWalkInstruction': '२० मिटरसम्म सुरक्षितसाथ छिटो हिँड्नुहोस्।',
      'getReady': 'तयार हुनुहोस्',
      'testRunning': 'परीक्षण भइरहेछ',
      'testCompleted': 'परीक्षण पूरा भयो',
      'startTest': 'परीक्षण शुरू गर्नुहोस्',
      'stopTest': 'परीक्षण रोक्नुहोस्',
      'higherOARisk': 'उच्च जोखिम',
      'notDiagnosis': 'AI स्क्रिनिङ • मेडिकल निदान होइन',
      'watchTutorial': 'ट्युटोरियल हेर्नुहोस्',
      'results': 'नतिजा',
      'screeningResults': 'स्क्रिनिङ नतिजा',
      'downloadReport': 'रिपोर्ट डाउनलोड गर्नुहोस्',
      'gotItStartTest': 'बुझेँ, परीक्षण सुरू गर्नुहोस्',
    },

    'nag': {
      'appTitle': 'MedSync OA Screening',
      'selectLanguage': 'Language choose kuribi',
      'language': 'Language',
      'movementHealth': 'Knee Health Checkup',
      'understandKneeMovement': 'Apni laga knee movement aro joint health samajhibi',
      'heroDescription': 'Knee problem aro sensor movement samiksha kure na check kuribole.',
      'howItWorks': 'MedSync kene kaam kure',
      'tellUsHowYouFeel': '1. Apni laga problem koibi',
      'tellUsHowYouFeelDescription': 'Knee pain aro chalibole tana problem answer kuribi.',
      'setUpMovementSensors': '2. Sensor connect kuribi',
      'setUpMovementSensorsDescription': 'KneeBand Bluetooth sensor connect kuribi.',
      'completeMovementTests': '3. Test pura kuribi',
      'completeMovementTestsDescription': '30s chair stand aro 20m speed walk test kuribi.',
      'getAiAssessment': '4. AI report lobi',
      'getAiAssessmentDescription': 'AI screening report joldi lobi.',
      'cancelScreening': 'Screening Cancel Kuribi',
      'step1Of4': 'Step 1 / 4',
      'step2Of4': 'Step 2 / 4',
      'step3Of4': 'Step 3 / 4',
      'step4Of4': 'Step 4 / 4',
      'continue': 'AAGETI JABI',
      'back': 'WAPAS JABI',
      'next': 'NEXT',
      'done': 'HOISE',
      'cancel': 'CANCEL',
      'start': 'SHURU KURIBI',
      'stop': 'RUKIBI',
      'patientAssessment': 'Patient Info',
      'patientAssessmentTitle': 'Apni laga problem koibi',
      'patientAssessmentSubtitle': 'Ei details sensor movement matha logote AI check kuribole ase.',
      'age': 'Umar',
      'sex': 'Male/Female',
      'female': 'Female',
      'male': 'Male',
      'preferNotToSay': 'Kobi na lage',
      'height': 'Height',
      'weight': 'Weight',
      'pain': 'Pain',
      'stiffness': 'Stiffness',
      'functionalDifficulty': 'Chalibole problem',
      'activityRelatedPain': 'Kaam kure time pain',
      'morningStiffness': 'Sokal time stiffness',
      'enterAge': 'Umar likhibi',
      'enterHeight': 'Height likhibi (cm)',
      'enterWeight': 'Weight likhibi (kg)',
      'selectSex': 'Male/Female choose kuribi',
      'ratePain': 'Pain score dibi (0 - 10)',
      'rateStiffness': 'Stiffness score dibi (0 - 10)',
      'rateDifficulty': 'Chalibole problem score dibi (0 - 10)',
      'startScreening': 'Screening Shuru Kuribi',
      'sensorSetup': 'Sensor Setup',
      'chairStand': '30 Second Chair Test',
      'fastWalk': 'Speed Walk 20m',
      'fastWalk20m': '20m Speed Walk',
      'no': 'Nai / Pain nai',
      'higherOARisk': 'High Risk',
      'notDiagnosis': 'AI Checkup • Doctor test nohoi',
      'watchTutorial': 'Tutorial chabole',
      'results': 'Result',
      'screeningResults': 'Screening Result',
      'downloadReport': 'Report Download Kuribi',
      'gotItStartTest': 'Samajhise, Start kuribi',
    },
  };
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLanguages.supported.any(
      (language) => language.code == locale.languageCode,
    );
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale.languageCode);
  }

  @override
  bool shouldReload(
    covariant LocalizationsDelegate<AppLocalizations> old,
  ) {
    return false;
  }
}